# 📘 Regular Expression (Regex) Important Patterns

Regular Expression (Regex) text mein **specific pattern ko search, match, extract ya remove** karne ke liye use hota hai.

---

## 1. Basic Regex Characters

| Pattern | Simple Meaning | Kya aa sakta hai? | Example |
|---|---|---|---|
| `\d` | 0 se 9 tak koi ek digit | 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 | `5` |
| `\d+` | 0–9 mein se ek ya zyada digits | 1, 25, 786, 2026 | `123` |
| `\D` | 0–9 ke ilawa koi ek character | a, B, @, #, space | `A` |
| `\w` | a-z, A-Z, 0-9 ya `_` mein se koi ek character | a, Z, 5, _ | `B` |
| `\w+` | a-z, A-Z, 0-9, `_` mein se ek ya zyada characters | Ali, user123, abc_12 | `Ali123` |
| `\W` | a-z, A-Z, 0-9 aur `_` ke ilawa koi ek character | @, #, !, space | `@` |
| `\s` | Koi ek whitespace | space, tab, new line | space |
| `\s+` | Ek ya zyada whitespaces | multiple spaces/newlines | `   ` |
| `\S` | Whitespace ke ilawa koi ek character | a, 5, @, # | `A` |
| `.` | Newline ke ilawa almost koi ek character | a, 5, @, # | `@` |
| `\.` | Actual dot `.` ko match karta hai | . | `.` |

---

## 2. Square Brackets `[]` Range / Character Set

Square brackets ka matlab hota hai ke **brackets ke andar diye gaye characters mein se koi ek character** match karo.

| Pattern | Exact Meaning | Example |
|---|---|---|
| `[0-9]` | 0 se 9 tak koi ek digit | `7` |
| `[0-9]+` | 0 se 9 tak ek ya zyada digits | `786` |
| `[a-z]` | a se z tak koi ek small letter | `g` |
| `[a-z]+` | a se z tak ek ya zyada small letters | `hello` |
| `[A-Z]` | A se Z tak koi ek capital letter | `H` |
| `[A-Z]+` | A se Z tak ek ya zyada capital letters | `HELLO` |
| `[a-zA-Z]` | a-z ya A-Z mein se koi ek letter | `a`, `G` |
| `[a-zA-Z]+` | Ek ya zyada English letters | `Sara` |
| `[a-zA-Z0-9]` | Letter ya 0-9 mein se koi ek character | `A`, `b`, `7` |
| `[^0-9]` | 0 se 9 ke ilawa koi ek character | `A`, `@` |
| `[^a-zA-Z]` | a-z aur A-Z ke ilawa koi ek character | `5`, `@`, `#` |

### Important Concept

Square brackets ke andar start mein `^` ka matlab **NOT** hota hai.

Example:

`[^0-9]`

Meaning:

**0 se 9 ke digits ke ilawa koi bhi character.**

---

## 3. Quantity Symbols Kitni Baar Match Karna Hai?

Quantity symbols batate hain ke koi character **kitni baar aa sakta hai**.

| Pattern | Meaning | Example |
|---|---|---|
| `\d` | 0–9 mein se exactly 1 digit | `5` |
| `\d+` | 0–9 mein se 1 ya zyada digits | `5`, `56`, `567` |
| `\d*` | 0–9 mein se 0 ya zyada digits | empty, `5`, `567` |
| `\d?` | 0–9 mein se 0 ya 1 digit | empty ya `5` |
| `\d{4}` | Exactly 4 digits | `2026` |
| `\d{2,4}` | Minimum 2 aur maximum 4 digits | `12`, `123`, `1234` |
| `\d{2,}` | Minimum 2 digits, maximum ki koi limit nahi | `12`, `123`, `123456` |

---

## 4. Start aur End Symbols

| Pattern | Meaning | Example |
|---|---|---|
| `^Hello` | Text `Hello` se start hona chahiye | `Hello Students` |
| `world$` | Text `world` par end hona chahiye | `Hello world` |

### `^` ki Do Meanings Yaad Rakhein

`^` ki meaning uski position par depend karti hai.

**Square brackets ke bahar:**

`^Hello`

Meaning: Text **Hello se start** hona chahiye.

**Square brackets ke andar:**

`[^0-9]`

Meaning: **0-9 ke ilawa** koi character.

---

## 5. OR Operator `|`

`|` ka matlab **OR** hota hai.

Example:

`cat|dog`

Meaning:

**cat OR dog**

Dono mein se koi bhi word match ho sakta hai.

Another example:

`http\S+|www\S+`

Meaning:

- `http\S+` → http se start hone wali URL
- `|` → OR
- `www\S+` → www se start hone wali URL

---

## 6. Parentheses `()` Grouping

Parentheses multiple patterns ko **ek group** mein combine karne ke liye use hote hain.

Example:

`(Mr|Mrs)`

Meaning:

**Mr OR Mrs**

Another example:

`(Mr|Mrs)\s\w+`

Breakdown:

- `(Mr|Mrs)` → Mr ya Mrs
- `\s` → ek space
- `\w+` → ek ya zyada word characters

Possible matches:

`Mr Ali`

`Mrs Sara`

---

## 7. Word Boundary `\b`

`\b` complete word ki **boundary** ko represent karta hai.

Example:

`\bcat\b`

Ye match karega:

`I have a cat`

Lekin ye match nahi karega:

`category`

Kyun ke humein complete word `cat` chahiye.

---

## 8. Escape Character `\`

Regex mein kuch characters ki special meaning hoti hai.

Agar humein un characters ko **actual character** ke taur par find karna ho to unke aage `\` lagate hain.

| Pattern | Actual Character |
|---|---|
| `\.` | . |
| `\+` | + |
| `\?` | ? |
| `\*` | * |
| `\(` | ( |
| `\)` | ) |
| `\$` | $ |

Example:

`\.`

Meaning:

**Actual dot `.` ko find karo.**

---

#  Easy Formula for Creating Regex Patterns

Examples:

- `\d` → 0-9 tak digit
- `[A-Z]` → A-Z tak capital letter
- `[a-z]` → a-z tak small letter
- `\w` → letter, digit ya underscore

### KITNA?

Woh character kitni baar chahiye?

Examples:

- `+` → 1 ya zyada
- `*` → 0 ya zyada
- `?` → 0 ya 1
- `{4}` → exactly 4
- `{2,4}` → minimum 2, maximum 4

---

## Example 1: Four Digits

Pattern:

`\d{4}`

Breakdown:

- `\d` → **KYA?** → 0 se 9 tak digit
- `{4}` → **KITNI?** → Exactly 4

Possible Match:

`2026`

---

## Example 2: Two Capital Letters

Pattern:

`[A-Z]{2}`

Breakdown:

- `[A-Z]` → **KYA?** → A se Z tak capital letter
- `{2}` → **KITNE?** → Exactly 2

Possible Matches:

`PK`

`US`

`AI`

---

## Example 3: Pakistani Phone Number

Pattern:

`\d{4}-\d{7}`

Breakdown:

- `\d{4}` → Exactly 4 digits
- `-` → Hyphen
- `\d{7}` → Exactly 7 digits

Possible Match:

`0300-1234567`

---

## Example 4: Simple Email Pattern

Pattern:

`\w+@\w+\.\w+`

Breakdown:

- `\w+` → Ek ya zyada word characters
- `@` → @ symbol
- `\w+` → Ek ya zyada word characters
- `\.` → Actual dot
- `\w+` → Ek ya zyada word characters

Possible Match:

`sara123@gmail.com`

---

In [1]:
import pandas as pd

In [2]:
hn = pd.read_csv("hacker_news.csv")

In [3]:
hn.head()

,id,title,url,num_points,num_comments,author,created_at
0,12224879,Interactive Dynamic Video,http://www.interactivedynamicvideo.com/,386,52,ne0phyte,8/4/2016 11:52
1,11964716,Florida DJs May Face Felony for April Fools' W...,http://www.thewire.com/entertainment/2013/04/f...,2,1,vezycash,6/23/2016 22:20
2,11919867,Technology ventures: From Idea to Enterprise,https://www.amazon.com/Technology-Ventures-Ent...,3,1,hswarna,6/17/2016 0:01
3,10301696,Note by Note: The Making of Steinway L1037 (2007),http://www.nytimes.com/2007/11/07/movies/07ste...,8,2,walterbell,9/30/2015 4:12
4,10482257,Title II kills investment? Comcast and other I...,http://arstechnica.com/business/2015/10/comcas...,53,22,Deinos,10/31/2015 9:48

In [4]:
hn.info()

<class 'pandas.DataFrame'>
RangeIndex: 20099 entries, 0 to 20098
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            20099 non-null  int64
 1   title         20099 non-null  str
 2   url           17659 non-null  str
 3   num_points    20099 non-null  int64
 4   num_comments  20099 non-null  int64
 5   author        20099 non-null  str
 6   created_at    20099 non-null  str
dtypes: int64(3), str(4)
memory usage: 3.7 MB

In [5]:
"I am khushboo and I am Trainer"[5:13]

'khushboo'

In [6]:
"This is khushboo and we are Learing R.E"[5:13]

'is khush'

In [7]:
string = "This is khushboo and we arer Learing R.E"
string[5:13]

'is khush'

In [8]:
"This is khushboo and we arer Learing R.E"[8:14]

'khushb'

In [9]:
import re

In [10]:
dir(re)

['A',
 'ASCII',
 'DEBUG',
 'DOTALL',
 'I',
 'IGNORECASE',
 'L',
 'LOCALE',
 'M',
 'MULTILINE',
 'Match',
 'NOFLAG',
 'Pattern',
 'PatternError',
 'RegexFlag',
 'S',
 'Scanner',
 'U',
 'UNICODE',
 'VERBOSE',
 'X',
 '_MAXCACHE',
 '_MAXCACHE2',
 '_ZeroSentinel',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_cache',
 '_cache2',
 '_casefix',
 '_compile',
 '_compile_template',
 '_compiler',
 '_constants',
 '_parser',
 '_pickle',
 '_special_chars_map',
 '_sre',
 '_zero_sentinel',
 'compile',
 'copyreg',
 'enum',
 'error',
 'escape',
 'findall',
 'finditer',
 'fullmatch',
 'functools',
 'match',
 'purge',
 'search',
 'split',
 'sub',
 'subn']

In [11]:
re.search("and","I Have Two Hands")

In [12]:
"I Have Two Hands"[12:15]

'and'

In [13]:
re.search("abc","I Have Two Hands")

In [14]:
print(re.search("abc","I Have Two Hands"))

None

In [15]:
if re.search("and","I Have Two Hands"):
    print("Done")

Done

In [16]:
if re.search("abc","I Have Two Hands"):
    print("Done")

In [17]:
hn["title"]

0                                Interactive Dynamic Video
1        Florida DJs May Face Felony for April Fools' W...
2             Technology ventures: From Idea to Enterprise
3        Note by Note: The Making of Steinway L1037 (2007)
4        Title II kills investment? Comcast and other I...
                               ...
20094    How Purism Avoids Intels Active Management Tec...
20095            YC Application Translated and Broken Down
20096    Microkernels are slow and Elvis didn't do no d...
20097                        How Product Hunt really works
20098    RoboBrowser: Your friendly neighborhood web sc...
Name: title, Length: 20099, dtype: str

In [18]:
title = hn["title"]
title

0                                Interactive Dynamic Video
1        Florida DJs May Face Felony for April Fools' W...
2             Technology ventures: From Idea to Enterprise
3        Note by Note: The Making of Steinway L1037 (2007)
4        Title II kills investment? Comcast and other I...
                               ...
20094    How Purism Avoids Intels Active Management Tec...
20095            YC Application Translated and Broken Down
20096    Microkernels are slow and Elvis didn't do no d...
20097                        How Product Hunt really works
20098    RoboBrowser: Your friendly neighborhood web sc...
Name: title, Length: 20099, dtype: str

In [19]:
"mend", "send", "bend"

"[msb]end" #mend, bend

'[msb]end'

In [20]:
pattern = "[Pp]ython"

In [21]:
count = 0

for i in title:
    if re.search(pattern, i):
        count += 1
        print(i)
        
count

From Python to Lua: Why We Switched
Ubuntu 16.04 LTS to Ship Without Python 2
Create a GUI Application Using Qt and Python in Minutes
How I Solved GCHQ's Xmas Card with Python and Pycosat. (Explanation and Source)
Unikernel Power Comes to Java, Node.js, Go, and Python Apps
Developing a computational pipeline using the asyncio module in Python 3
Show HN: Minimal, modern embedded V8 for Python
Python integration for the Duktape Javascript interpreter
Python 3 on Google App Engine flexible environment now in beta
IronPython 3 (python for .net) development restarted
Cysignals: signal handling (SIGINT, SIGSEGV, ) for calling C from Python
Ask HN: Would you be interested in an embeddable, lightweight subset of Python?
A Hello World Server in Python
Microsoft shipped Python code in 1996
Moore Foundation provides grant for Contiuum's Python Numba and Dask Compilers
Integrate Python and .NET
Face Swap (C++ / Python): Meet Ted Trump, Donald Clinton and Hillary Cruz
ImportPython
Show HN: Fabulous: Print images in terminal with Python
Python 3.5 Async IO, Matmul and Unpack Features for PyPy: Only Bug Fixes Left
Scipy Lecture Notes  Learn numerics, science, and data with Python
PeachPy: Assembly Code Generation in High-Level Python
500 Lines or Less  A Python Interpreter Written in Python
Peak detection on signals in Python
PLY (Python Lex-Yacc)  To Write a Parser in Python
Visualizing relationships between Python packages
Debugging of CPython processes with gdb
Marshmallow: Simplified object serialization for Python
Pycraft: Minecraft engine in Python
Using Google's Python Client Library to Authorise Your Desktop App with OAuth2
Exhaustive list of All Python Books (Updated)
PyThalesians: Python Open Source Financial Library
Show HN: Python Crash Course
Python wats
Free 2 Player Game [Python][Angular]
Python 3.6 proposal, PEP 525: Asynchronous Generators
Hubness-aware kNN in Python
Typeshed: static types for the Python standard library
Show HN: An experimental Python to C#/Go/Ruby/JS transpiler
Python 3  Function Overloading with singledispatch
Welcome to the Python Engineering blog
Learn data science in python by taking online course
How async/await works in Python 3.5
Ubuntu Drops Python 2.7 from the Default Install in 16.04
An OpenCV-based document scanner in Python
AWS Lambda Supports Python, Versioning, Scheduled Jobs, and 5 Minute Functions
Python 3.5 and Multitasking
Show HN: Graphene  GraphQL framework for Python
Show HN: Dplython, dplyr data manipulation for python
Show HN: Automatically import or install modules when they're needed in IPython
Polar watches/sportbands Python API
Thoughts on the future of Python and graphical interfaces
Authorization for humans (Python Package)
Writing custom type systems for Python in Prolog
Introducing TrumpScript  Make Python Great Again
A fast PostgreSQL client library for Python: 3x faster than psycopg2
See Python, See Python Go, Go Python Go
Python 3 support in scientific Python projects
Why I'm not leaving Python for Go (2012)
Kickstarter for funding Micropython port to ESP8266
Show HN: I created a Python framework for fast Slack bot development
Python 3 comes to Scrapy
Show HN: Space Shooter  Retro Game Recreated Using Python
Python Data Science Handbook Supplemental Materials
Python 3 in 2016
Python: Generators, Coroutines, Native Coroutines and Async/Await
Show HN: Learn the Amazon Echo with Python
Using attrs for everything in Python
How to build and deploy a simple Facebook Messenger bot with Python and Flask
Go bridges to JavaScript and Python
Preview the Python Serverless Microframework for AWS
Keras 1.0  Python deep learning framework
PLE: Reinforcement Learning Environment in Python
Show HN: How to add jitter to a plot using Python's matplotlib and seaborn
PyBridge - Reuse your Python code in native Android applications
Python 3.6 dict becomes compact and keywords become ordered
Memspector: Inspect memory usage of Python functions
Installing TensorFlow with Python 3 on EC2 GPU Instances
Proving that Javas and Pythons sorting algorithm is broken
MicroPython 1.5 (small Python implementation for IoT, etc.)
Show HN: TeachCraft  Learning Python Through Minecraft
Show HN: A super simple webcrawler framework written in Python
Ask HN: A statically typed alternative to Python with batteries included
Book: Deep Learning with Python
Angular 2 coming to Java, Python and PHP
Legofy  Python program to make an image to look as if it was created with Legos
Using Native Python Libraries in Lambda
Python 8 will be the next major Python version
Interactive Interpreter Tab Completion in Python
Python on Pebble
Changing the Culture of Python at Facebook [video]
Ask HN: Fun and interesting Python things to do or learn?
Ask HN: How do you provide your Python dependencies in production in 2016?
Show HN: Python 3 pyGtk graphical curve and surface fitter
Show HN: Python program to clean up handwritten notes
Document Clustering with Python
Show HN: Affirm  Improved error messages for Python assert statements
A native Python IDE built for data science
Show HN: Pycraft  learn Python with Minecraft
'New' Python modules of 2015
Recreational Maths in Python
DQN for Beginners in 200 lines of python code to play Flappy Bird with Keras
Building Powerful Frameworks in Python
Show HN: Venv2docker  create a docker image from a python virtualenv
Show HN: First Release of Transcrypt Python3.5 to JavaScript Compiler
C Is Manly, Python Is for N00bs:How False Stereotypes Turn into Technical Truths
Python implementation of statistical Dependency parsing using SVM by @rj_here
Python Decorators in 12 Steps (2012)
Python 3.5.0
EasyMake  one python file instead tons of Makefile locs
Pineapple  A standalone front end to IPython for Mac
A tool to search for Python code using jQuery-like selectors
Show HN: Automated algorithm translation for Python, C++, C#, JS
Meet Connexion: Zalando's Open-Source REST Framework for Python
Visual profiler for Python
Show HN: Update your requirements.txt file with Pur in Python
Left-pad for Python (how could we have lived all this time without it?)
CPython internals: Codewalk through the Python interpreter source code (2014)
Python, Machine Learning, and Language Wars
Code that will break in Python 4
Python-like programming language interpreter written in Python
Introducing Yosai: A Security Framework for Python Applications
Py-Videocore: Python Library for GPGPU on Raspberry Pi
let in python (2014)
MicroPython, a few years on
New string formatting in Python
Ptpython  better than ipython or bpython?
Measure the Real Size of Any Python Object
Ask HN: OO book for old Python hacker?
C++ Has Become More Pythonic (2014)
Jarvis: Personal Assistant in Python
Python Internals: PyObject
An SMS Center with Python, Kannel and a GSM Modem
The Python Paradox
How I defeated an anti-tamper APK with some Python and a homemade Smali emulator
An Introduction to Mocking in Python
Writing Pythonic code pays off
Show HN: Insideout  does this new approach to Python packaging makes sense?
Comparing Python Command-Line Parsing Libraries  Argparse, Docopt, and Click
Python: Why cant we write list.len()?
An Introduction to Scientific Python (and a Bit of the Maths Behind It)
Feather: A Fast On-Disk Format for Data Frames for R and Python
From Python to Go and Back Again
How to kill yourself in Python
Why Python 3 Exists
Show HN: Stack overflow command line client added support to python 2
Python one-liner to compare two files (conditions apply)
Python vs. C/C++ in embedded systems
The origins of the class Meta idiom in python
Python is Better than Ruby
Web Service Efficiency at Instagram with Python
Crypto and SSL toolkit for python (M2Crypto)
PythonJobs.com
Wheres Susi? Airborne Orangutan Tracking with Python and React.js
Transition to Python4 won't be like Python3(we've learned our lesson)
David Beazley  Python Concurrency from the Ground Up: Live  PyCon 2015
Ask HN: How to automate Python apps deployment?
Moving Away from Python 2
Python vs. Julia Observations
Show HN: Decorating: Animated pulsed for your slow functions in Python

160

In [22]:
pattern = "[Pp]ython"

boolean = title.str.contains(pattern)
boolean.sum()

np.int64(160)

In [23]:
boolean

0        False
1        False
2        False
3        False
4        False
         ...
20094    False
20095    False
20096    False
20097    False
20098    False
Name: title, Length: 20099, dtype: bool

In [24]:
title[boolean]

102                    From Python to Lua: Why We Switched
103              Ubuntu 16.04 LTS to Ship Without Python 2
144      Create a GUI Application Using Qt and Python i...
196      How I Solved GCHQ's Xmas Card with Python and ...
436      Unikernel Power Comes to Java, Node.js, Go, an...
                               ...
19597    David Beazley  Python Concurrency from the Gro...
19852      Ask HN: How to automate Python apps deployment?
19862                            Moving Away from Python 2
19980                        Python vs. Julia Observations
19998    Show HN: Decorating: Animated pulsed for your ...
Name: title, Length: 160, dtype: str

In [25]:
pattern = "[Rr]uby"

title[title.str.contains(pattern)]

190                     Ruby on Google AppEngine Goes Beta
484           Related: Pure Ruby Relational Algebra Engine
1388     Show HN: HTTPalooza  Ruby's greatest HTTP clie...
1949     Rewriting a Ruby C Extension in Rust: How a Na...
2022     Show HN: CrashBreak  Reproduce exceptions as f...
2163                   Ruby 2.3 Is Only 4% Faster than 2.2
2306     Websocket Shootout: Clojure, C++, Elixir, Go, ...
2620                       Why Startups Use Ruby on Rails?
2645     Ask HN: Should I continue working a Ruby gem f...
3290     Ruby on Rails and the importance of being stup...
3749     Telegram.org Bot Platform Webhooks Server, for...
3874     Warp Directory (wd) unix command line tool for...
4026     OS X 10.11 Ruby / Rails users can install ther...
4163     Charles Nutter of JRuby Banned by Rubinius for...
4602     Quiz: Ruby or Rails? Matz and DHH were not abl...
5832     Show HN: An experimental Python to C#/Go/Ruby/...
6180     Shrine  A new solution for handling file uploa...
7171     JRuby+Truffle: Why its important to optimise t...
7235                                        Ruby or Rails?
7671                    How I hunted the most odd ruby bug
7776     Elixir obsoletes Ruby, Erlang and Clojure in o...
7870                            Elixir and Ruby Comparison
8502     Show HN: Di-ary  a math note-taking app built ...
10212               Ruby has been fast enough for 13 years
11060    Show HN: VeryAnts: Probabilistic Integer Arith...
11534                             The Ruby Code of Conduct
11622    FasterPath: Faster Pathname Handling for Ruby ...
12061       Ask HN: What's your favorite ruby HTTP client?
12091    Show HN: Automated Bundle Update with Descript...
12114                                         Awesome Ruby
12543    Ruby Bug: SecureRandom should try /dev/urandom...
12987    Show HN: Klipse  code evaluator pluggable on a...
13550    Matz: I cannot accept the CoC for the Ruby com...
13650                  Programs that rewrite Ruby programs
14798                  Ruby Wrapper for Telegram's Bot API
14980                    A Ruby gem for genetic algorithms
16093                          Master Ruby Web APIs Is Out
16149         Ruru: native Ruby extensions written in Rust
16327                   Make Ruby Great Again [transcript]
16422                                 Object Oriented Ruby
16536                           Ruby Deoptimization Engine
16875                         Video: Make Ruby Great Again
17072    A coupon/deals site built using Roda gem for Ruby
17510                        Table Flip on Ruby Exceptions
18877    Using Rust with Ruby, a Deep Dive with Yehuda ...
19077                           Python is Better than Ruby
19224                    Modern concurrency tools for Ruby
19743    Using a Neural Network to Train a Ruby Twitter...
Name: title, dtype: str

In [26]:
hn['title'].loc[2022]

'Show HN: CrashBreak  Reproduce exceptions as failing tests in Ruby'

In [27]:
# 1000-2999,   1900, 2800

In [28]:
pattern = "[12][0-9][0-9][0-9]"

title[title.str.contains(pattern)]

3        Note by Note: The Making of Steinway L1037 (2007)
34                        The reverse job applicant (2010)
50         Ask HN: Which framework for a CRUD app in 2016?
59            2015 in review  1 year after I quit blogging
80       Apple Watch Scooped Up Over Half the Smartwatc...
                               ...
20032    Things I Wont Work With: Dioxygen Difluoride (...
20049    Study: US is an oligarchy, not a democracy (2014)
20075    Tips from a Pro: An Introduction to Microscopi...
20081                 Usenet, what have you become? (2012)
20082    Colma, Calif., Is a Town of 2.2 Square Miles, ...
Name: title, Length: 1143, dtype: str

In [29]:
hn['title'].loc[20075]

'Tips from a Pro: An Introduction to Microscopic Photography (2015)'

# Numeric Quantifier

a{3} -> The character `a` three times

a{3,5} ->The character `a` three, four or five times

a{,3} ->The character `a` zero, one, two or three times

a{8,} ->The character `a` eight or more times

In [30]:
re.search("a{2}","I am Saad")

In [31]:
re.search("a{2}","I am Sad")

In [32]:
re.search("a{2,}","I am Saaaaaaaaaaaaaaaaaaaaaaad")

In [33]:
# pattern = "[12][0-9][0-9][0-9]"
pattern = "[12][0-9]{3}"

title[title.str.contains(pattern)]

3        Note by Note: The Making of Steinway L1037 (2007)
34                        The reverse job applicant (2010)
50         Ask HN: Which framework for a CRUD app in 2016?
59            2015 in review  1 year after I quit blogging
80       Apple Watch Scooped Up Over Half the Smartwatc...
                               ...
20032    Things I Wont Work With: Dioxygen Difluoride (...
20049    Study: US is an oligarchy, not a democracy (2014)
20075    Tips from a Pro: An Introduction to Microscopi...
20081                 Usenet, what have you become? (2012)
20082    Colma, Calif., Is a Town of 2.2 Square Miles, ...
Name: title, Length: 1143, dtype: str

# Character classes

* `set` ->[fud] either f,u or d
* `range` -> [a-e] any of the charachter a,b,c,d or e
* `range` -> [0-3] any of the charachter 0,1,2 or 3
* `range` -> [A-Z] any uppercase letter
* `set+range` -> [A-Za-z] any uppercase or lower case letter[Aa-Zz]
* `Digit` -> **`\d`** any digit character(equivalent to [0-9])
* `Word` -> **`\w`** any digit, uppercase, lowercase or underscore character (equivalent to [A-Za-z0-9_]). Does not include any special character 
* `Whitepace` -> **`\s`** any space, tab or linebreak character
* `Dot` -> **`.`**  any character except newline

In [34]:
# pattern = "[12][0-9][0-9][0-9]"
pattern = "[12]\d{3}"

title[title.str.contains(pattern)]

3        Note by Note: The Making of Steinway L1037 (2007)
34                        The reverse job applicant (2010)
50         Ask HN: Which framework for a CRUD app in 2016?
59            2015 in review  1 year after I quit blogging
80       Apple Watch Scooped Up Over Half the Smartwatc...
                               ...
20032    Things I Wont Work With: Dioxygen Difluoride (...
20049    Study: US is an oligarchy, not a democracy (2014)
20075    Tips from a Pro: An Introduction to Microscopi...
20081                 Usenet, what have you become? (2012)
20082    Colma, Calif., Is a Town of 2.2 Square Miles, ...
Name: title, Length: 1143, dtype: str

# Single Characters Quantifier

a* -> equivalent to a{0,} zero or more

a+ -> equivalent to a{1,} one or more

a? -> equivalent to a{0,1} zero or one

In [35]:
print("khushboo \n \tsaleem")

khushboo
 	saleem

In [36]:
re.search(".","khushboo \n \tsaleem")

In [37]:
re.search("..","khushboo \n \tsaleem")

In [38]:
re.search(".{1,}","khushboo \n \tsaleem")

In [39]:
re.search(".+","khushboo \n \tsaleem")

In [40]:
re.search("e-{0,1}mail","email")

In [41]:
re.search("e-?mail","e-mail")

In [42]:
re.search("e-?mail","email")

In [43]:
# email, e-mail

pattern = "e-?mail"

title[title.str.contains(pattern)]

119      Show HN: Send an email from your shell to your...
313          Disposable emails for safe spam free shopping
1361     Ask HN: Doing cold emails? helps us prove this...
1750     Protect yourself from spam, bots and phishing ...
2421                    Ashley Madison hack treating email
                               ...
18098    House panel looking into Reddit post about Cli...
18583    Mailgen  Generates clean, responsive HTML for ...
18847    Show HN: Crisp iOS keyboard for email and text...
19303    Ask HN: Why big email providers don't sign the...
19446    Tell HN: Secure email provider Riseup will run...
Name: title, Length: 86, dtype: str

In [44]:
# email, e-mail

pattern = "(e-?mail)"

email = title.str.extract(pattern)
email.value_counts()

0
email     81
e-mail     5
Name: count, dtype: int64

In [45]:
# email, e-mail

pattern = "e-?(mail)"

email = title.str.extract(pattern)
email.value_counts()

0
mail    86
Name: count, dtype: int64

In [46]:
# [pdf], [video], [png], [a], [0], [A]

pattern = "\[\w+\]"

title[title.str.contains(pattern)]

66       Analysis of 114 propaganda sources from ISIS, ...
100      Munich Gunman Got Weapon from the Darknet [Ger...
159           File indexing and searching for Plan 9 [pdf]
162      Attack on Kunduz Trauma Centre, Afghanistan  I...
195                 [Beta] Speedtest.net  HTML5 Speed Test
                               ...
19763    TSA can now force you to go through body scann...
19867                       Using Pony for Fintech [video]
19947                                Swift Reversing [pdf]
19979    WSJ/Dowjones Announce Unauthorized Access Betw...
20089    Users Really Do Plug in USB Drives They Find [...
Name: title, Length: 444, dtype: str

In [47]:

pattern = "(\[\w+\])"

email = title.str.extract(pattern)
email.value_counts()

0
[pdf]            276
[video]          111
[audio]            3
[2015]             3
[slides]           2
[beta]             2
[2014]             2
[German]           1
[Beta]             1
[satire]           1
[song]             1
[ANNOUNCE]         1
[Videos]           1
[videos]           1
[Australian]       1
[SPA]              1
[CSS]              1
[2008]             1
[React]            1
[Python]           1
[Excerpt]          1
[Live]             1
[crash]            1
[gif]              1
[png]              1
[Infograph]        1
[Petition]         1
[blank]            1
[USA]              1
[updated]          1
[GOST]             1
[coffee]           1
[Map]              1
[JavaScript]       1
[repost]           1
[much]             1
[survey]           1
[map]              1
[5]                1
[1996]             1
[NSFW]             1
[comic]            1
[transcript]       1
[ask]              1
[detainee]         1
[SpaceX]           1
[Skinnywhale]      1
[Benchmark]        1
[viz]              1
[HBR]              1
[Challenge]        1
[Ubuntu]           1
Name: count, dtype: int64

In [48]:
# email, e-mail

pattern = "\[(\w+)\]"

email = title.str.extract(pattern)
email.value_counts()

0
pdf            276
video          111
audio            3
2015             3
slides           2
beta             2
2014             2
German           1
Beta             1
satire           1
song             1
ANNOUNCE         1
Videos           1
videos           1
Australian       1
SPA              1
CSS              1
2008             1
React            1
Python           1
Excerpt          1
Live             1
crash            1
gif              1
png              1
Infograph        1
Petition         1
blank            1
USA              1
updated          1
GOST             1
coffee           1
Map              1
JavaScript       1
repost           1
much             1
survey           1
map              1
5                1
1996             1
NSFW             1
comic            1
transcript       1
ask              1
detainee         1
SpaceX           1
Skinnywhale      1
Benchmark        1
viz              1
HBR              1
Challenge        1
Ubuntu           1
Name: count, dtype: int64

In [49]:
# email, e-mail

pattern = "\[\w+\]"

email = title.str.extract(pattern)
email.value_counts()

ValueError: pattern contains no capture groups

# Negative Class

* `Negative Set` -> [^fud] any charachter except f,u or d
* `Negative Set` -> [^1-3Z\s] any charachter except 1,2,3,Z or Whitespace character
* `Negative Digit` -> \D any charachter except Digit character
* `Negative Word` -> \W any charachter except word character
* `Negative whitespace` -> \S any charachter except space character

In [50]:
text = hn["title"][0]

print("Original Text:", text)

result = re.findall(r"[^fud]", text)

print("Result:", result)

Original Text: Interactive Dynamic Video
Result: ['I', 'n', 't', 'e', 'r', 'a', 'c', 't', 'i', 'v', 'e', ' ', 'D', 'y', 'n', 'a', 'm', 'i', 'c', ' ', 'V', 'i', 'e', 'o']

In [51]:
result = re.findall(r"[^1-3Z\s]", text)

print("Result:", result)

Result: ['I', 'n', 't', 'e', 'r', 'a', 'c', 't', 'i', 'v', 'e', 'D', 'y', 'n', 'a', 'm', 'i', 'c', 'V', 'i', 'd', 'e', 'o']

In [52]:
result = re.findall(r"\D", text)

result

['I',
 'n',
 't',
 'e',
 'r',
 'a',
 'c',
 't',
 'i',
 'v',
 'e',
 ' ',
 'D',
 'y',
 'n',
 'a',
 'm',
 'i',
 'c',
 ' ',
 'V',
 'i',
 'd',
 'e',
 'o']

In [53]:
text = "Hello!!!"

result = re.sub("!", "", text)

print(result)

Hello

In [54]:
text = "Python 123"

result = re.sub(r"\d", "", text)

print(result)

Python

In [55]:

clean_titles = []

for title in hn["title"]:
    
    # Letters aur spaces ke ilawa sab remove karega
    clean = re.sub(r"[^a-zA-Z\s]", "", title)
    
    clean_titles.append(clean)

hn["clean_title"] = clean_titles

hn[["title", "clean_title"]]

,title,clean_title
0,Interactive Dynamic Video,Interactive Dynamic Video
1,Florida DJs May Face Felony for April Fools' W...,Florida DJs May Face Felony for April Fools Wa...
2,Technology ventures: From Idea to Enterprise,Technology ventures From Idea to Enterprise
3,Note by Note: The Making of Steinway L1037 (2007),Note by Note The Making of Steinway L
4,Title II kills investment? Comcast and other I...,Title II kills investment Comcast and other IS...
...,...,...
20094,How Purism Avoids Intels Active Management Tec...,How Purism Avoids Intels Active Management Tec...
20095,YC Application Translated and Broken Down,YC Application Translated and Broken Down
20096,Microkernels are slow and Elvis didn't do no d...,Microkernels are slow and Elvis didnt do no drugs
20097,How Product Hunt really works,How Product Hunt really works
20098,RoboBrowser: Your friendly neighborhood web sc...,RoboBrowser Your friendly neighborhood web scr...

## Question 1: Clean Author Names

Task: Using the author column, remove all characters except letters, numbers, and underscore _ using re.sub().

## Question 2 Remove Extra Spaces from Titles

Task: Some text may contain more than one whitespace. Using re.sub(), replace one or more whitespace characters with a single space.

In [56]:
# Clean authors store karne ke liye empty list
clean_authors = []

# Author column ke har author par loop chalega
for author in hn["author"]:

    # Author ko string mein convert kar rahe hain
    author = str(author)

    # \W letters, numbers aur _ ke ilawa characters ko find karega
    # "" un characters ko remove karega
    clean = re.sub(r"\W", "", author)

    # Clean author ko list mein add kar rahe hain
    clean_authors.append(clean)

# New column bana rahe hain
hn["clean_author"] = clean_authors

# Original aur cleaned author show kar rahe hain
hn[["author", "clean_author"]]

              author   clean_author
0           ne0phyte       ne0phyte
1           vezycash       vezycash
2            hswarna        hswarna
3         walterbell     walterbell
4             Deinos         Deinos
...              ...            ...
20094  AdmiralAsshat  AdmiralAsshat
20095       zreitano       zreitano
20096    vezzy-fnord     vezzyfnord
20097          brw12          brw12
20098      pmoriarty      pmoriarty

[20099 rows x 2 columns]

In [57]:
# Clean titles store karne ke liye empty list
single_space_titles = []

# Har title par loop chalega
for title in hn["title"]:

    # \s+ ek ya zyada whitespace ko find karega
    # " " unko single space se replace karega
    clean = re.sub(r"\s+", " ", title)

    # Clean title ko list mein add kar rahe hain
    single_space_titles.append(clean)

# New column bana rahe hain
hn["title_single_space"] = single_space_titles

# Original aur cleaned title show kar rahe hain
hn[["title", "title_single_space"]]

,title,title_single_space
0,Interactive Dynamic Video,Interactive Dynamic Video
1,Florida DJs May Face Felony for April Fools' W...,Florida DJs May Face Felony for April Fools' W...
2,Technology ventures: From Idea to Enterprise,Technology ventures: From Idea to Enterprise
3,Note by Note: The Making of Steinway L1037 (2007),Note by Note: The Making of Steinway L1037 (2007)
4,Title II kills investment? Comcast and other I...,Title II kills investment? Comcast and other I...
...,...,...
20094,How Purism Avoids Intels Active Management Tec...,How Purism Avoids Intels Active Management Tec...
20095,YC Application Translated and Broken Down,YC Application Translated and Broken Down
20096,Microkernels are slow and Elvis didn't do no d...,Microkernels are slow and Elvis didn't do no d...
20097,How Product Hunt really works,How Product Hunt really works
20098,RoboBrowser: Your friendly neighborhood web sc...,RoboBrowser: Your friendly neighborhood web sc...